### ISSUE TITLE
"press enter to clear" fails on macOS

### ISSUE THREAD

**Issue by greyspectrum** [ojensen5115/pw#3]
After a password is copied to the clipboard and "enter" is pressed, `pw` exits as though the clipboard has been cleared, but the password remains in the clipboard.

System: macOS High Sierra 10.13.2

I'm not entirely sure what's responsible, since rust-clipboard is cross-platform:

https://github.com/aweinstock314/rust-clipboard

**Comment by ojensen5115** [comment]
This has been addressed in https://github.com/ojensen5115/pw/commit/76eaa5a425e6125449cd091043e5c611d901e841
