### ISSUE TITLE
Enable sqlite dump to backup credentials.

### ISSUE THREAD

**Issue by greyspectrum** [ojensen5115/pw#4]
Currently, users can "show" individual credentials, but there is no way to dump all of the credentials to stdout, which could be useful in order to create a local, offline backup, such as on a usb stick.

This would be useful for disaster recovery, in case a user deletes a credential accidentally, or if the Keybase service were to become unavailable for some reason.

It looks as though Stable Rust [doesn't include](https://stackoverflow.com/questions/42594102/return-type-for-rusqlite-mappedrows) the "dump" function in rusqlite, but the nightly release does.

When "dump" trickles down to Stable Rust, this would be a great feature, I think. I would be up for implementing this if you're interested in the PR.

**Comment by ojensen5115** [comment]
`pw` stores credentials in a sqlite file, which by default is located in `/keybase/private/[username]/pw.dat`, though you can modify this path by editing the configuration in `.pwrc`. If you want to save a backup / dump of your credentials, just copy your `pw.dat` file to whatever media you want: it's a vanilla sqlite file.

If you choose to do so, be cautious about how you handle / where you put this file: once outside of your private keybase folder you are handling a file that contains your credentials in plaintext.
